# aesthetics
background-opacity = 0.92
background-blur=16
background=#000000

# colours
theme = Adwaita Dark
bold-is-bright = true

# typography
font-size=12
font-thicken=true
font-thicken-strength=1
font-family = "MesloLGS NF"
adjust-cell-height=1

# Cursor
cursor-style = block
cursor-style-blink = true
cursor-invert-fg-bg = true
shell-integration-features = no-cursor

# extras
copy-on-select = clipboard
focus-follows-mouse = true
link-url = true

# macOS-specific settings
macos-titlebar-style = tabs
macos-option-as-alt = true
macos-icon = blueprint

# mouse
mouse-hide-while-typing = true
